features=["trip_distance", "driver_distance", "event_hour", "driver_gps_accuracy","historical_rides"]
target="is_completed"
test_size=0.2

[random_forest]
n_estimators=[300,400]
max_depth=[30,50]
n_jobs=[-1]
random_state=[42]
bootstrap=[true,false]
